blueprint:
  name: Anunciar Novo E-mail
  description: Anuncia o assunto do último e-mail recebido.
  domain: automation
  input:
    onde_anunciar:
      selector:
        entity:
          filter:
            - integration: alexa_media
              domain: media_player
          multiple: true
      name: Onde Anunciar
      required: true
      default: []
      description: Escolha as Alexas
    volume:
      selector:
        number:
          min: 0.1
          max: 1
          step: 0.1
      default: 0.9
      name: Volume
      description: Escolha o volume do anúncio (padrão 90%)
mode: queued
sequence:
  - service: media_player.volume_set
    target:
      entity_id: '{{ onde_anunciar }}'
    data:
      volume_level: '{{ volume }}'
  - delay: '00:00:01'
  - service: notify.alexa_media
    target: '{{ onde_anunciar }}'
    data:
      message: >
        Você tem um novo e-mail com o assunto: {{ states['sensor.ultimo_titulo_email'].state }}.
      data:
        type: announce
  - delay: '00:00:15'
  - service: notify.alexa_media
    target: '{{ onde_anunciar }}'
    data:
      message: >
        Remetente: {{ states['sensor.ultimo_titulo_email'].attributes['Remetente'] }}.
      data:
        type: announce
  - delay: '00:00:25'
  - service: media_player.volume_set
    target:
      entity_id: '{{ onde_anunciar }}'
    data:
      volume_level: 0.3
icon: mdi:email
