blueprint:
  name: Anunciar via Alexa o email
  description: Anuncia via alexa titulo da ultimo email recebido
  domain: script
mode: queued
fields:
  onde_anunciar:
    selector:
      entity:
        filter:
          - integration: alexa_media
            domain: media_player
        multiple: true
    name: Onde Anunciar
    required: true
    default: []
    description: Escolha as Alexas
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 0.5
    name: Volume
    description: Escolha o volume do anúncio (padrão 50%)
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{ volume }}"
    target:
      entity_id: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: >
        Você tem um novo e-mail com o assunto: {{ states['sensor.ultimo_titulo_email'].state }}.
      data:                      
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0      
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn
