blueprint:
  name: Anunciar via Alexa com Base em Sensor
  description: Anuncia o estado de um sensor em todas as caixas Echo selecionadas
  domain: script
mode: queued
fields:
  sensor:
    selector:
      entity:
        domain: sensor
    name: Sensor
    description: Selecione o sensor cujo estado será anunciado
    default: sensor.steps_daily  # Dispositivo fixo sensor.steps_daily
    required: true
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 0.9  # Definindo um valor padrão de volume
    name: Volume
    description: Escolha o volume do anúncio (padrão 90%)
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{ volume }}"
    target:
      entity_id: sensor.steps_daily  # Dispositivo fixo sensor.steps_daily
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: >
        Você deu o total de {{ states(sensor) }} Passos. Seu Objetivo é 8000. Você alcançou {{ ((states(sensor) | int / 8000) * 100) | round(2) }}% do seu objetivo.
      data:
        type: announce
      target: sensor.steps_daily  # Dispositivo fixo sensor.steps_daily
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      entity_id: sensor.steps_daily  # Dispositivo fixo sensor.steps_daily
icon: mdi:bullhorn
