blueprint:
  name: Anunciar via Alexa com Base em Sensor
  description: Anuncia o estado de três sensores em todas as caixas Echo selecionadas
  domain: script
mode: queued
fields:
  onde_anunciar:
    selector:
      entity:
        filter:
          - integration: alexa_media
            domain: media_player
        multiple: true
    name: Onde Anunciar
    required: true
    default: []
    description: Escolha as Alexas
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 0.9
    name: Volume
    description: Escolha o volume do anúncio (padrão 90%)
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{ volume }}"
    target:
      entity_id: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: >
        {% set flight_info = states['sensor.flightradar24_current_in_area'].attributes['flights'][0] %}

        Voo {{ flight_info['flight.flight_number'] }} da empresa {{ flight_info['airline'] }} com origem {{ flight_info['airport_origin_name'] }} foi detectado em nosso espaço aéreo.

      data:
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 25
      milliseconds: 0 
      message: >
        {% set flight_info = states['sensor.flightradar24_current_in_area'].attributes['flights'][0] %}

        Com destino {{ flight_info['airport_destination_city'] }} aeroporto {{ flight_info['airport_destination_name'] }} com previsão de chegada para as {{ flight_info['flight.time_scheduled_arrival'] | timestamp_custom('%H:%M') }} 

      data:
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 25
      milliseconds: 0                
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn
