blueprint:
  name: Anunciar via Alexa com Base em Sensor
  description: Anuncia o estado de um sensor em todas as caixas Echo selecionadas
  domain: script
mode: queued
fields:
  sensor:
    selector:
      entity:
        domain: sensor
    name: Sensor
    description: Selecione o sensor cujo estado será anunciado
    required: true
  onde_anunciar:
    selector:
      entity:
        filter:
          - integration: alexa_media
            domain: media_player
        multiple: true
    name: Onde Anunciar
    required: true
    default: []
    description: Escolha as Alexas
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.9  # Definindo o volume como 90%
    target:
      entity_id: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: >
        Você deu o total de {{ states(sensor) }} Passos. Seu Objetivo é 8000. Você alcançou {{ ((states(sensor) | int / 8000) * 100) | round(2) }}% do seu objetivo.
      data:
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn
