blueprint:
  name: Anunciar via Alexa com Base em Sensor
  description: Anuncia o estado de dois sensores em todas as caixas Echo selecionadas
  domain: script
mode: queued
fields:
  sensor1:
    selector:
      entity:
        domain: sensor
    name: Sensor 1
    description: Selecione o primeiro sensor cujo estado será anunciado
    required: true
  sensor2:
    selector:
      entity:
        domain: sensor
    name: Sensor 2
    description: Selecione o segundo sensor cujo estado será anunciado
    required: true
  onde_anunciar:
    selector:
      entity:
        filter:
          - integration: alexa_media
            domain: media_player
        multiple: true
    name: Onde Anunciar
    required: true
    default: []
    description: Escolha as Alexas
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 0.9
    name: Volume
    description: Escolha o volume do anúncio (padrão 90%)
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{ volume }}"
    target:
      entity_id: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: >
        Sensor 1 - Você deu o total de {{ states(sensor1) }} Passos. Seu Objetivo é 8000. Você alcançou {{ ((states(sensor1) | int / 8000) * 100) | round(2) }}% do seu objetivo.
      data:
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: >
        Sensor 2 - Você bebeu o total de  {{ states(sensor2) }} Litros. Seu Objetivo é 3. Você alcançou {{ ((states(sensor2) | int / 4) * 100) | round(2) }}% do seu objetivo.
      data:
        type: announce
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0    
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn
